import type { ProfileSnapshot } from './types';

export const fallbackSnapshot: ProfileSnapshot = {
  generatedAt: new Date().toISOString(),
  source: 'fallback',
  profile: {
    login: 'pacobaco',
    name: 'Juan Rodriguez',
    bio: 'Systems design across AI, valuation, networks, and publication surfaces.',
    avatarUrl: 'https://github.com/pacobaco.png',
    followers: 0,
    following: 0,
    publicRepos: 0,
    htmlUrl: 'https://github.com/pacobaco',
  },
  repos: [
    {
      name: 'act-gp',
      description: 'Multilingual AI generation and orchestration.',
      href: 'https://github.com/pacobaco/act-gp',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'TypeScript',
      topics: ['ai', 'generation', 'agentic'],
      updatedAt: new Date().toISOString(),
      layer: 'Intelligence',
      archived: false,
      fork: false,
    },
    {
      name: 'flyometer',
      description: 'Model indexing and AI signal tracking.',
      href: 'https://github.com/pacobaco/flyometer',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'Python',
      topics: ['ai', 'models', 'ranking'],
      updatedAt: new Date().toISOString(),
      layer: 'Intelligence',
      archived: false,
      fork: false,
    },
    {
      name: 'navstone',
      description: 'REIT index and valuation platform.',
      href: 'https://github.com/pacobaco/navstone',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'TypeScript',
      topics: ['reit', 'valuation', 'finance'],
      updatedAt: new Date().toISOString(),
      layer: 'Financial Systems',
      archived: false,
      fork: false,
    },
    {
      name: 'treasuryprofiler',
      description: 'Treasury structure and balance intelligence.',
      href: 'https://github.com/pacobaco/treasuryprofiler',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'Python',
      topics: ['treasury', 'profiling', 'finance'],
      updatedAt: new Date().toISOString(),
      layer: 'Financial Systems',
      archived: false,
      fork: false,
    },
    {
      name: 'assetnexus',
      description: 'Graph-based asset intelligence.',
      href: 'https://github.com/pacobaco/assetnexus',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'TypeScript',
      topics: ['graph', 'assets', 'identity'],
      updatedAt: new Date().toISOString(),
      layer: 'Network & Identity',
      archived: false,
      fork: false,
    },
    {
      name: 'ODE',
      description: 'Smart lock and control layer experiments.',
      href: 'https://github.com/pacobaco/ODE',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'C++',
      topics: ['iot', 'infrastructure'],
      updatedAt: new Date().toISOString(),
      layer: 'Infrastructure',
      archived: false,
      fork: false,
    },
  ],
  stats: {
    totalRepos: 6,
    totalStars: 0,
    activeLast90Days: 6,
    layers: {
      Intelligence: 2,
      'Financial Systems': 2,
      'Network & Identity': 1,
      Infrastructure: 1,
      Publication: 0,
      Other: 0,
    },
  },
};
