import type { ProfileSnapshot } from './types';

export const fallbackSnapshot: ProfileSnapshot = {
  generatedAt: new Date().toISOString(),
  source: 'fallback',
  profile: {
    login: 'pacobaco',
    name: 'Juan Rodriguez',
    bio: 'Research, infrastructure, finance, identity systems, and AI routed as a unified operating surface.',
    avatarUrl: 'https://avatars.githubusercontent.com/u/1?v=4',
    followers: 0,
    following: 0,
    publicRepos: 0,
    htmlUrl: 'https://github.com/pacobaco',
  },
  repos: [
    {
      name: 'navstone',
      description: 'REIT index and valuation platform.',
      href: 'https://github.com/pacobaco/navstone',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'TypeScript',
      topics: ['reit', 'valuation', 'finance'],
      updatedAt: new Date().toISOString(),
      layer: 'Financial Systems',
      archived: false,
      fork: false,
    },
    {
      name: 'flyometer',
      description: 'AI model indexing and ranking surface.',
      href: 'https://github.com/pacobaco/flyometer',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'TypeScript',
      topics: ['ai', 'models', 'index'],
      updatedAt: new Date().toISOString(),
      layer: 'Intelligence',
      archived: false,
      fork: false,
    },
    {
      name: 'assetnexus',
      description: 'Asset graph intelligence and profiling.',
      href: 'https://github.com/pacobaco/assetnexus',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'Python',
      topics: ['graph', 'identity', 'network'],
      updatedAt: new Date().toISOString(),
      layer: 'Network & Identity',
      archived: false,
      fork: false,
    },
    {
      name: 'wh-uzi',
      description: 'Telemetry and systems infrastructure.',
      href: 'https://github.com/pacobaco/wh-uzi',
      homepage: null,
      stars: 0,
      forks: 0,
      watchers: 0,
      language: 'Python',
      topics: ['telemetry', 'infrastructure'],
      updatedAt: new Date().toISOString(),
      layer: 'Infrastructure',
      archived: false,
      fork: false,
    }
  ],
  stats: {
    totalRepos: 4,
    totalStars: 0,
    activeLast90Days: 4,
    layers: {
      Intelligence: 1,
      'Financial Systems': 1,
      'Network & Identity': 1,
      Infrastructure: 1,
      Publication: 0,
      Other: 0,
    },
  },
};
